import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import api from "../api";

/**
 * Defining the State Type
 */
interface ProductState {
  items: any[];
  status: "idle" | "loading" | "succeeded" | "failed";
  error: string | null;
}

const initialState: ProductState = {
  items: [],
  status: "idle",
  error: null,
};

/**
 * Async Thunk for Fetching Products
 * 
 * createAsyncThunk handles the promise lifecycle for you (pending, fulfilled, rejected).
 * It uses the 'api' (Axios instance) to make the network request.
 */
export const fetchProducts = createAsyncThunk(
  "products/fetchProducts",
  async (_, { rejectWithValue }) => {
    try {
      // Using our central Axios instance
      const response = await api.get("/products");
      // Axios returns the actual data in 'response.data'
      return response.data;
    } catch (error: any) {
      // If the request fails, return the error message
      return rejectWithValue(
        error.response?.data?.message || "Failed to fetch products"
      );
    }
  }
);

/**
 * Creating the Product Slice
 */
const productSlice = createSlice({
  name: "products",
  initialState,
  reducers: {
    // Standard reducers for synchronous actions go here
    clearProducts: (state) => {
      state.items = [];
    },
  },
  extraReducers: (builder) => {
    // Handling asynchronous actions generated by createAsyncThunk
    builder
      .addCase(fetchProducts.pending, (state) => {
        state.status = "loading";
      })
      .addCase(fetchProducts.fulfilled, (state, action) => {
        state.status = "succeeded";
        state.items = action.payload; // Update the products list
      })
      .addCase(fetchProducts.rejected, (state, action) => {
        state.status = "failed";
        state.error = action.payload as string; // Store the error message
      });
  },
});

export const { clearProducts } = productSlice.actions;
export default productSlice.reducer;
