export const categories = [
  {
    name: "Skincare",
    slug: "skincare",
    description: "Daily essentials for healthy, radiant skin.",
  },
  {
    name: "Makeup",
    slug: "makeup",
    description: "Buildable makeup for a polished finish.",
  },
  {
    name: "Haircare",
    slug: "haircare",
    description: "Nourishing formulas for every hair type.",
  },
  {
    name: "Bodycare",
    slug: "bodycare",
    description: "Hydrating care for smooth, soft skin.",
  },
  {
    name: "Fragrance",
    slug: "fragrance",
    description: "Signature scents for every mood.",
  },
];

export const products = [
  {
    name: "Velvet Matte Lipstick",
    description: "Long-lasting matte lipstick with vibrant pigment.",
    price: 38,
    comparePrice: 45,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["vegan", "cruelty-free"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["castor oil", "vitamin e"],
    routineStep: "makeup",
    rating: 4.5,
    reviewCount: 10,
    isNew: false,
    isBestSeller: true,
  },
  {
    name: "Radiance Facial Serum",
    description: "Brightening vitamin C serum that reduces dark spots.",
    price: 89,
    comparePrice: 99,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["vegan", "cruelty-free", "clean"],
    skinTypes: ["normal", "combination"],
    concerns: ["dark spots", "dullness"],
    ingredients: ["vitamin c", "hyaluronic acid"],
    routineStep: "serum",
    rating: 4.7,
    reviewCount: 8,
    isNew: true,
    isBestSeller: true,
  },
  {
    name: "Warm Nude Eye Palette",
    description: "Highly pigmented nude eye shadow palette.",
    price: 64,
    comparePrice: 74,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1512496115851-a1c8e04d2448?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["cruelty-free"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["mica", "jojoba oil"],
    routineStep: "makeup",
    rating: 4.8,
    reviewCount: 22,
    isNew: false,
    isBestSeller: true,
  },
  {
    name: "Luminous Barrier Cream",
    description: "Deep moisturizing skincare cream enriched with ceramides.",
    price: 72,
    comparePrice: 82,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["vegan", "cruelty-free", "clean"],
    skinTypes: ["dry", "sensitive"],
    concerns: ["dryness", "barrier repair"],
    ingredients: ["ceramides", "squalane"],
    routineStep: "moisturizer",
    rating: 4.3,
    reviewCount: 14,
    isNew: false,
    isBestSeller: false,
  },
  {
    name: "Rose Water Toner",
    description: "Refreshing rose water toner that hydrates and balances pH.",
    price: 45,
    comparePrice: 55,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["clean", "vegan"],
    skinTypes: ["normal", "dry"],
    concerns: ["redness", "dehydration"],
    ingredients: ["rose water", "glycerin"],
    routineStep: "toner",
    rating: 4.6,
    reviewCount: 19,
    isNew: true,
    isBestSeller: false,
  },
  {
    name: "Argan Oil Hair Serum",
    description: "Nourishing argan oil serum that tames frizz and adds shine.",
    price: 52,
    comparePrice: 60,
    categorySlug: "haircare",
    images: [
      "https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["cruelty-free"],
    skinTypes: ["all"],
    concerns: ["frizz"],
    ingredients: ["argan oil", "vitamin e"],
    routineStep: "treatment",
    rating: 4.4,
    reviewCount: 11,
    isNew: false,
    isBestSeller: false,
  },
  {
    name: "SPF 50 Sunscreen Drops",
    description: "Lightweight, non-greasy sunscreen with broad-spectrum SPF 50.",
    price: 48,
    comparePrice: 56,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["vegan", "clean"],
    skinTypes: ["all"],
    concerns: ["sun protection"],
    ingredients: ["zinc oxide", "niacinamide"],
    routineStep: "sunscreen",
    rating: 4.9,
    reviewCount: 35,
    isNew: true,
    isBestSeller: true,
  },
  {
    name: "Liquid Foundation",
    description: "Medium-coverage foundation with a natural skin-like finish.",
    price: 55,
    comparePrice: 65,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1596462502278-27bf85033c5a?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["cruelty-free"],
    skinTypes: ["normal", "combination"],
    concerns: ["uneven tone"],
    ingredients: ["silica", "vitamin e"],
    routineStep: "makeup",
    rating: 4.2,
    reviewCount: 17,
    isNew: false,
    isBestSeller: false,
  },
  {
    name: "Hydrating Aloe Gel Cleanser",
    description: "Gentle gel cleanser that hydrates while removing impurities.",
    price: 34,
    comparePrice: 42,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["clean", "vegan"],
    skinTypes: ["dry", "sensitive"],
    concerns: ["dryness", "redness"],
    ingredients: ["aloe vera", "panthenol"],
    routineStep: "cleanser",
    rating: 4.6,
    reviewCount: 16,
    isNew: true,
    isBestSeller: false,
  },
  {
    name: "Cloud Skin Moisturizer",
    description: "Weightless gel-cream moisturizer for all-day comfort.",
    price: 58,
    comparePrice: 68,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["cruelty-free", "clean"],
    skinTypes: ["normal", "combination", "oily"],
    concerns: ["oil control", "dehydration"],
    ingredients: ["green tea", "hyaluronic acid"],
    routineStep: "moisturizer",
    rating: 4.4,
    reviewCount: 12,
    isNew: true,
    isBestSeller: false,
  },
  {
    name: "Mineral Blush Stick",
    description: "Creamy blush stick with a soft, natural flush.",
    price: 32,
    comparePrice: 38,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["cruelty-free"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["shea butter", "mica"],
    routineStep: "makeup",
    rating: 4.3,
    reviewCount: 9,
    isNew: false,
    isBestSeller: false,
  },
  {
    name: "Brow Sculpting Gel",
    description: "Flexible hold brow gel for natural, feathered brows.",
    price: 26,
    comparePrice: 30,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["vegan", "cruelty-free"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["panthenol", "aloe"],
    routineStep: "makeup",
    rating: 4.5,
    reviewCount: 18,
    isNew: false,
    isBestSeller: true,
  },
  {
    name: "Repairing Hair Mask",
    description: "Deep conditioning mask for dry and damaged hair.",
    price: 44,
    comparePrice: 54,
    categorySlug: "haircare",
    images: [
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["clean", "cruelty-free"],
    skinTypes: ["all"],
    concerns: ["damage repair"],
    ingredients: ["argan oil", "keratin"],
    routineStep: "mask",
    rating: 4.7,
    reviewCount: 21,
    isNew: true,
    isBestSeller: false,
  },
  {
    name: "Sea Salt Body Scrub",
    description: "Exfoliating scrub that softens and smooths skin.",
    price: 38,
    comparePrice: 46,
    categorySlug: "bodycare",
    images: [
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["vegan"],
    skinTypes: ["all"],
    concerns: ["rough texture"],
    ingredients: ["sea salt", "coconut oil"],
    routineStep: "exfoliate",
    rating: 4.2,
    reviewCount: 7,
    isNew: false,
    isBestSeller: false,
  },
  {
    name: "Silk Touch Body Lotion",
    description: "Lightweight lotion with a satin finish and soft scent.",
    price: 29,
    comparePrice: 36,
    categorySlug: "bodycare",
    images: [
      "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["clean"],
    skinTypes: ["dry", "normal"],
    concerns: ["dryness"],
    ingredients: ["shea butter", "jojoba oil"],
    routineStep: "moisturizer",
    rating: 4.1,
    reviewCount: 5,
    isNew: false,
    isBestSeller: false,
  },
  {
    name: "Noir Bloom Eau de Parfum",
    description: "A warm floral fragrance with notes of rose and amber.",
    price: 96,
    comparePrice: 110,
    categorySlug: "fragrance",
    images: [
      "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["cruelty-free"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["rose absolute", "amber"],
    routineStep: "fragrance",
    rating: 4.8,
    reviewCount: 26,
    isNew: true,
    isBestSeller: true,
  },
];
