export const categories = [
  {
    name: "Skincare",
    slug: "skincare",
    description: "Daily essentials for healthy, radiant skin.",
  },
  {
    name: "Makeup",
    slug: "makeup",
    description: "Buildable makeup for a polished finish.",
  },
  {
    name: "Haircare",
    slug: "haircare",
    description: "Nourishing formulas for every hair type.",
  },
  {
    name: "Bodycare",
    slug: "bodycare",
    description: "Hydrating care for smooth, soft skin.",
  },
  {
    name: "Fragrance",
    slug: "fragrance",
    description: "Signature scents for every mood.",
  },
  {
    name: "Hair Mask",
    slug: "hairmask",
    description: "Intensive treatments for healthy hair.",
  },
];

export const products = [
  // ─────────────── SKINCARE ───────────────
  {
    name: "Radiance Vitamin C Serum",
    description: "Brightening vitamin C serum that visibly reduces dark spots and evens skin tone for a luminous glow.",
    price: 89,
    comparePrice: 99,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["NEW", "BEST SELLER"],
    skinTypes: ["normal", "combination"],
    concerns: ["dark spots", "dullness"],
    ingredients: ["vitamin c", "hyaluronic acid", "ferulic acid"],
    routineStep: "serum",
    rating: 4.7,
    reviewCount: 128,
    isNew: true,
    isBestSeller: true,
    countInStock: 45,
  },
  {
    name: "Luminous Ceramide Barrier Cream",
    description: "Deep moisturizing cream enriched with ceramides to restore the skin barrier and lock in hydration all day.",
    price: 72,
    comparePrice: 82,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c?q=80&w=800&auto=format&fit=crop",
    ],
    tags: [],
    skinTypes: ["dry", "sensitive"],
    concerns: ["dryness", "barrier repair"],
    ingredients: ["ceramides", "squalane", "shea butter"],
    routineStep: "moisturizer",
    rating: 4.3,
    reviewCount: 94,
    isNew: false,
    isBestSeller: false,
    countInStock: 28,
  },
  {
    name: "Rose Water Balancing Toner",
    description: "Refreshing rose water toner that hydrates, balances pH and preps skin for the next step in your routine.",
    price: 45,
    comparePrice: 55,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1601065873952-f999b9a62da7?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["NEW"],
    skinTypes: ["normal", "dry"],
    concerns: ["redness", "dehydration"],
    ingredients: ["rose water", "glycerin", "niacinamide"],
    routineStep: "toner",
    rating: 4.6,
    reviewCount: 77,
    isNew: true,
    isBestSeller: false,
    countInStock: 60,
  },
  {
    name: "SPF 50 Invisible Sunscreen Drops",
    description: "Lightweight, non-greasy, broad-spectrum SPF 50 sunscreen that blends invisibly into any skin tone.",
    price: 48,
    comparePrice: 56,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1689414480286-aae7c21fe1e2?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["BEST SELLER"],
    skinTypes: ["all"],
    concerns: ["sun protection", "anti-aging"],
    ingredients: ["zinc oxide", "niacinamide", "vitamin e"],
    routineStep: "sunscreen",
    rating: 4.9,
    reviewCount: 310,
    isNew: true,
    isBestSeller: true,
    countInStock: 90,
  },
  {
    name: "Hydrating Aloe Gel Cleanser",
    description: "Gentle gel cleanser infused with aloe vera and panthenol that removes impurities without stripping the skin.",
    price: 34,
    comparePrice: 42,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1763622499218-37fdfc7a590a?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["NEW"],
    skinTypes: ["dry", "sensitive"],
    concerns: ["dryness", "redness"],
    ingredients: ["aloe vera", "panthenol", "chamomile extract"],
    routineStep: "cleanser",
    rating: 4.6,
    reviewCount: 65,
    isNew: true,
    isBestSeller: false,
    countInStock: 75,
  },
  {
    name: "Cloud Skin Weightless Moisturizer",
    description: "A whisper-light gel-cream that delivers all-day hydration without heaviness — perfect for oily skin.",
    price: 58,
    comparePrice: 68,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1584091825078-752292c7763a?q=80&w=800&auto=format&fit=crop",
    ],
    tags: [],
    skinTypes: ["normal", "combination", "oily"],
    concerns: ["oil control", "dehydration"],
    ingredients: ["green tea extract", "hyaluronic acid", "snow mushroom"],
    routineStep: "moisturizer",
    rating: 4.4,
    reviewCount: 52,
    isNew: false,
    isBestSeller: false,
    countInStock: 38,
  },
  {
    name: "Retinol Renewal Night Cream",
    description: "Advanced retinol night cream that accelerates cell turnover, smoothing fine lines while you sleep.",
    price: 95,
    comparePrice: 115,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab12?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["BEST SELLER"],
    skinTypes: ["normal", "combination", "dry"],
    concerns: ["anti-aging", "fine lines", "wrinkles"],
    ingredients: ["retinol", "peptides", "squalane", "vitamin e"],
    routineStep: "moisturizer",
    rating: 4.8,
    reviewCount: 204,
    isNew: false,
    isBestSeller: true,
    countInStock: 22,
  },
  {
    name: "Niacinamide 10% Pore Serum",
    description: "High-concentration niacinamide to minimize pores, control oil, and improve uneven skin texture over time.",
    price: 62,
    comparePrice: 72,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=800&auto=format&fit=crop",
    ],
    tags: [],
    skinTypes: ["oily", "combination"],
    concerns: ["large pores", "oil control", "uneven texture"],
    ingredients: ["niacinamide 10%", "zinc", "hyaluronic acid"],
    routineStep: "serum",
    rating: 4.5,
    reviewCount: 173,
    isNew: false,
    isBestSeller: false,
    countInStock: 55,
  },
  {
    name: "Peptide Eye Cream",
    description: "Targeted peptide cream that firms and depuffs the delicate under-eye area, reducing dark circles.",
    price: 78,
    comparePrice: 90,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["NEW"],
    skinTypes: ["all"],
    concerns: ["dark circles", "puffiness", "anti-aging"],
    ingredients: ["matrixyl 3000", "caffeine", "vitamin k"],
    routineStep: "eye cream",
    rating: 4.6,
    reviewCount: 88,
    isNew: true,
    isBestSeller: false,
    countInStock: 30,
  },
  {
    name: "Glycolic Acid Resurfacing Toner",
    description: "Chemical exfoliant with 7% glycolic acid to dissolve dead cells, brighten, and smooth skin texture.",
    price: 55,
    comparePrice: 65,
    categorySlug: "skincare",
    images: [
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=800&auto=format&fit=crop",
    ],
    tags: [],
    skinTypes: ["normal", "oily", "combination"],
    concerns: ["dullness", "uneven texture", "acne scars"],
    ingredients: ["glycolic acid 7%", "rose extract", "aloe"],
    routineStep: "toner",
    rating: 4.7,
    reviewCount: 141,
    isNew: false,
    isBestSeller: false,
    countInStock: 42,
  },

  // ─────────────── MAKEUP ───────────────
  {
    name: "Velvet Matte Lipstick",
    description: "Long-lasting matte lipstick with ultra-vibrant pigment that wears comfortably for 12 hours.",
    price: 38,
    comparePrice: 45,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["BEST SELLER"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["castor oil", "vitamin e", "jojoba oil"],
    routineStep: "makeup",
    rating: 4.5,
    reviewCount: 188,
    isNew: false,
    isBestSeller: true,
    countInStock: 65,
  },
  {
    name: "Warm Nude Eye Shadow Palette",
    description: "12-shade highly pigmented nude palette with matte, satin, and foil finishes for endless eye looks.",
    price: 64,
    comparePrice: 74,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1512496115851-a1c8e04d2448?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["BEST SELLER"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["mica", "jojoba oil", "vitamin e"],
    routineStep: "makeup",
    rating: 4.8,
    reviewCount: 322,
    isNew: false,
    isBestSeller: true,
    countInStock: 40,
  },
  {
    name: "Radiant Skin Liquid Foundation",
    description: "Medium-buildable coverage foundation with a natural, skin-like finish. Available in 40 shades.",
    price: 55,
    comparePrice: 65,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1557205465-f3762edea6d3?q=80&w=800&auto=format&fit=crop",
    ],
    tags: [],
    skinTypes: ["normal", "combination"],
    concerns: ["uneven tone", "coverage"],
    ingredients: ["silica", "vitamin e", "hyaluronic acid"],
    routineStep: "makeup",
    rating: 4.2,
    reviewCount: 147,
    isNew: false,
    isBestSeller: false,
    countInStock: 35,
  },
  {
    name: "Creamy Mineral Blush Stick",
    description: "Buildable blush stick with a soft, natural flush. Blends effortlessly with fingers or a brush.",
    price: 32,
    comparePrice: 38,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1515688594390-b649af70d282?q=80&w=800&auto=format&fit=crop",
    ],
    tags: [],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["shea butter", "mica", "vitamin c"],
    routineStep: "makeup",
    rating: 4.3,
    reviewCount: 69,
    isNew: false,
    isBestSeller: false,
    countInStock: 50,
  },
  {
    name: "Brow Sculpting Clear Gel",
    description: "Long-wearing brow gel that grooms brows with flexible hold for a naturally feathered look.",
    price: 26,
    comparePrice: 30,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1594465919760-441fe5ad0cbf?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["BEST SELLER"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["panthenol", "aloe vera", "rice bran wax"],
    routineStep: "makeup",
    rating: 4.5,
    reviewCount: 118,
    isNew: false,
    isBestSeller: true,
    countInStock: 70,
  },
  {
    name: "Glass Skin Setting Spray",
    description: "Dewy finish setting spray that locks in makeup for 16 hours and imparts a glass-skin glow.",
    price: 36,
    comparePrice: 44,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1621333100656-1f6e0903328e?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["NEW"],
    skinTypes: ["normal", "dry", "combination"],
    concerns: ["longevity", "dullness"],
    ingredients: ["glycerin", "sodium hyaluronate", "aloe extract"],
    routineStep: "makeup",
    rating: 4.6,
    reviewCount: 211,
    isNew: true,
    isBestSeller: false,
    countInStock: 55,
  },
  {
    name: "Lash Amplify Volumizing Mascara",
    description: "Fiber-infused mascara formula that adds dramatic volume and length without clumping.",
    price: 30,
    comparePrice: 36,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1631214524020-3c69ca09c5ca?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["BEST SELLER"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["beeswax", "vitamin b5", "black iron oxide"],
    routineStep: "makeup",
    rating: 4.7,
    reviewCount: 289,
    isNew: false,
    isBestSeller: true,
    countInStock: 80,
  },
  {
    name: "Pro Contour & Highlight Kit",
    description: "A versatile palette for sculpting and brightening. Includes 6 blendable shades for all skin tones.",
    price: 49,
    comparePrice: 59,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1522338140262-f46f5912018a?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["PROFESSIONAL"],
    skinTypes: ["all"],
    concerns: ["sculpting", "definition"],
    ingredients: ["mica", "magnesium stearate", "vitamin e"],
    routineStep: "makeup",
    rating: 4.6,
    reviewCount: 156,
    isNew: false,
    isBestSeller: false,
    countInStock: 25,
  },
  {
    name: "Silk Finish Setting Powder",
    description: "Micro-fine translucent powder that blurs imperfections and controls shine for a soft-focus finish.",
    price: 34,
    comparePrice: 40,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1590439474864-39930df601b1?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["CLEAN"],
    skinTypes: ["oily", "combination"],
    concerns: ["oil control", "large pores"],
    ingredients: ["corn starch", "silica", "aloe leaf extract"],
    routineStep: "makeup",
    rating: 4.5,
    reviewCount: 92,
    isNew: true,
    isBestSeller: false,
    countInStock: 45,
  },
  {
    name: "Glow Cheek Tint",
    description: "A water-based cheek stain that provides a long-lasting, natural-looking flush of color.",
    price: 26,
    comparePrice: 32,
    categorySlug: "makeup",
    images: [
      "https://images.unsplash.com/photo-1591360236630-4989679693bc?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["VEGAN"],
    skinTypes: ["all"],
    concerns: ["dullness"],
    ingredients: ["water", "glycerin", "hibiscus extract"],
    routineStep: "makeup",
    rating: 4.4,
    reviewCount: 78,
    isNew: false,
    isBestSeller: false,
    countInStock: 60,
  },

  // ─────────────── HAIRCARE ───────────────
  {
    name: "Argan Oil Frizz-Control Serum",
    description: "Nourishing argan oil serum that tames frizz, seals split ends and adds high-gloss shine.",
    price: 52,
    comparePrice: 60,
    categorySlug: "haircare",
    images: [
      "https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=800&auto=format&fit=crop",
    ],
    tags: [],
    skinTypes: ["all"],
    concerns: ["frizz", "damage"],
    ingredients: ["argan oil", "vitamin e", "silk proteins"],
    routineStep: "treatment",
    rating: 4.4,
    reviewCount: 81,
    isNew: false,
    isBestSeller: false,
    countInStock: 40,
  },
  {
    name: "Repairing Keratin Hair Mask",
    description: "Intensive deep conditioning mask with keratin and argan oil that restores shine to dry, damaged hair.",
    price: 44,
    comparePrice: 54,
    categorySlug: "haircare",
    images: [
      "https://images.unsplash.com/photo-1519735891097-3b8a330aeecb?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["NEW"],
    skinTypes: ["all"],
    concerns: ["damage repair", "dryness"],
    ingredients: ["argan oil", "keratin", "biotin"],
    routineStep: "mask",
    rating: 4.7,
    reviewCount: 121,
    isNew: true,
    isBestSeller: false,
    countInStock: 25,
  },
  {
    name: "Volumizing Sea Salt Spray",
    description: "Get effortles beach waves with this mineral-rich salt spray. Adds texture and volume without stiffness.",
    price: 28,
    comparePrice: 34,
    categorySlug: "haircare",
    images: [
      "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["BEST SELLER"],
    skinTypes: ["all"],
    concerns: ["volume", "texture"],
    ingredients: ["sea salt", "kelp extract", "aloe vera"],
    routineStep: "styling",
    rating: 4.5,
    reviewCount: 89,
    isNew: false,
    isBestSeller: true,
    countInStock: 50,
  },
  {
    name: "Scalp Revitalizing Oil",
    description: "A blend of rosemary and peppermint oils to stimulate the scalp and promote healthy hair growth.",
    price: 42,
    comparePrice: 48,
    categorySlug: "haircare",
    images: [
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["NATURAL"],
    skinTypes: ["all"],
    concerns: ["hair thinning", "dry scalp"],
    ingredients: ["rosemary oil", "peppermint oil", "castor oil"],
    routineStep: "treatment",
    rating: 4.8,
    reviewCount: 145,
    isNew: true,
    isBestSeller: true,
    countInStock: 30,
  },
  {
    name: "Hydrating Coconut Shampoo",
    description: "Gently cleanses and hydrates dry hair with the power of coconut milk and vitamins.",
    price: 24,
    comparePrice: 30,
    categorySlug: "haircare",
    images: [
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["SULFATE FREE"],
    skinTypes: ["all"],
    concerns: ["dryness"],
    ingredients: ["coconut milk", "vitamin b5", "aloe"],
    routineStep: "cleanse",
    rating: 4.4,
    reviewCount: 210,
    isNew: false,
    isBestSeller: false,
    countInStock: 100,
  },
  {
    name: "Nourishing Avocado Conditioner",
    description: "Deeply conditions and detangles hair leaving it soft, shiny and manageable.",
    price: 24,
    comparePrice: 30,
    categorySlug: "haircare",
    images: [
      "https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["SILICONE FREE"],
    skinTypes: ["all"],
    concerns: ["tangles", "frizz"],
    ingredients: ["avocado oil", "shea butter", "vitamin e"],
    routineStep: "condition",
    rating: 4.5,
    reviewCount: 185,
    isNew: false,
    isBestSeller: false,
    countInStock: 85,
  },
  {
    name: "Silver Brightening Shampoo",
    description: "Neutralizes brassy tones in blonde, silver and grey hair for a cool-toned finish.",
    price: 32,
    comparePrice: 38,
    categorySlug: "haircare",
    images: [
      "https://images.unsplash.com/photo-1585232004423-244e0e6904e3?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["COLOR CARE"],
    skinTypes: ["all"],
    concerns: ["brassiness", "color vibrancy"],
    ingredients: ["violet pigments", "sunflower extract", "keratin"],
    routineStep: "cleanse",
    rating: 4.7,
    reviewCount: 112,
    isNew: true,
    isBestSeller: false,
    countInStock: 40,
  },
  {
    name: "Thermal Protectant Spray",
    description: "Shields hair from damage caused by heat styling tools up to 450°F.",
    price: 26,
    comparePrice: 32,
    categorySlug: "haircare",
    images: [
      "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a3ef?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["HEAT PROTECTION"],
    skinTypes: ["all"],
    concerns: ["heat damage", "breakage"],
    ingredients: ["wheat protein", "panthenol", "silk amino acids"],
    routineStep: "styling",
    rating: 4.6,
    reviewCount: 178,
    isNew: false,
    isBestSeller: true,
    countInStock: 65,
  },

  // ─────────────── FRAGRANCE ───────────────
  {
    name: "Noir Bloom Eau de Parfum",
    description: "A warm, intoxicating floral fragrance with heart notes of rose, iris and a base of amber and sandalwood.",
    price: 96,
    comparePrice: 110,
    categorySlug: "fragrance",
    images: [
      "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["BEST SELLER"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["rose absolute", "amber", "sandalwood"],
    routineStep: "fragrance",
    rating: 4.8,
    reviewCount: 196,
    isNew: true,
    isBestSeller: true,
    countInStock: 20,
  },
  {
    name: "Solar Citrus Cologne",
    description: "Bright and uplifting notes of bergamot, neroli and sea salt. Captures the essence of summer.",
    price: 75,
    comparePrice: 85,
    categorySlug: "fragrance",
    images: [
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["UNISEX"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["bergamot essence", "neroli boost", "musk"],
    routineStep: "fragrance",
    rating: 4.6,
    reviewCount: 124,
    isNew: true,
    isBestSeller: false,
    countInStock: 35,
  },
  {
    name: "Velvet Oud Intense",
    description: "A rich, mysterious blend of rare oud wood, smoky incense and dark patchouli.",
    price: 120,
    comparePrice: 140,
    categorySlug: "fragrance",
    images: [
      "https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["LUXURY"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["oud wood", "patchouli", "incense"],
    routineStep: "fragrance",
    rating: 4.9,
    reviewCount: 87,
    isNew: false,
    isBestSeller: true,
    countInStock: 15,
  },
  {
    name: "Midnight Jasmine Elixir",
    description: "Heady jasmine sambac paired with creamy vanilla and a hint of pink pepper.",
    price: 88,
    comparePrice: 98,
    categorySlug: "fragrance",
    images: [
      "https://images.unsplash.com/photo-1590736704728-f4730bb30770?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["FLORAL"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["jasmine absolute", "vanilla bean", "pink pepper"],
    routineStep: "fragrance",
    rating: 4.7,
    reviewCount: 143,
    isNew: true,
    isBestSeller: false,
    countInStock: 25,
  },
  {
    name: "Desert Sage & Sandalwood",
    description: "Earthwy and grounding. Notes of wild sage, white sandalwood and dry cedarwood.",
    price: 82,
    comparePrice: 92,
    categorySlug: "fragrance",
    images: [
      "https://images.unsplash.com/photo-1616948055600-a12117573c5d?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["EARTHY"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["sage oil", "sandalwood", "cedarwood"],
    routineStep: "fragrance",
    rating: 4.5,
    reviewCount: 62,
    isNew: false,
    isBestSeller: false,
    countInStock: 40,
  },
  {
    name: "Vanilla Silk Mist",
    description: "A light and airy hair and body mist with the comforting scent of pure vanilla and coconut.",
    price: 35,
    comparePrice: 42,
    categorySlug: "fragrance",
    images: [
      "https://images.unsplash.com/photo-1615033166141-942618995394?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["SWEET"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["vanilla extract", "coconut water", "aloe"],
    routineStep: "fragrance",
    rating: 4.4,
    reviewCount: 231,
    isNew: true,
    isBestSeller: true,
    countInStock: 120,
  },
  {
    name: "Wild Rose Petal",
    description: "The essence of a freshly bloomed rose garden. Delicate, romantic and fresh.",
    price: 78,
    comparePrice: 88,
    categorySlug: "fragrance",
    images: [
      "https://images.unsplash.com/photo-1563170351-be32388e0c84?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["ROMANTIC"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["rose water", "peony", "white musk"],
    routineStep: "fragrance",
    rating: 4.6,
    reviewCount: 95,
    isNew: false,
    isBestSeller: false,
    countInStock: 50,
  },
  {
    name: "Oceanic Breeze EDP",
    description: "Crisp aquatic notes blended with driftwood and sea salt. Refreshing and clean.",
    price: 72,
    comparePrice: 80,
    categorySlug: "fragrance",
    images: [
      "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["AQUATIC"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["marine accord", "sea salt", "oakmoss"],
    routineStep: "fragrance",
    rating: 4.4,
    reviewCount: 108,
    isNew: false,
    isBestSeller: false,
    countInStock: 45,
  },

  // ─────────────── BODYCARE ───────────────
  {
    name: "Sea Salt Exfoliating Body Scrub",
    description: "Mineral-rich sea salt scrub blended with coconut oil to slough away dead skin and reveal silky softness.",
    price: 38,
    comparePrice: 46,
    categorySlug: "bodycare",
    images: [
      "https://images.unsplash.com/photo-1683944433023-027a3f443ae4?q=80&w=800&auto=format&fit=crop",
    ],
    tags: [],
    skinTypes: ["all"],
    concerns: ["rough texture"],
    ingredients: ["sea salt", "coconut oil", "vitamin e"],
    routineStep: "exfoliate",
    rating: 4.2,
    reviewCount: 57,
    isNew: false,
    isBestSeller: false,
    countInStock: 20,
  },
  {
    name: "Silk Touch Nourishing Body Lotion",
    description: "Lightweight lotion enriched with shea butter and jojoba oil — absorbs fast with a satin finish.",
    price: 29,
    comparePrice: 36,
    categorySlug: "bodycare",
    images: [
      "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?q=80&w=800&auto=format&fit=crop",
    ],
    tags: [],
    skinTypes: ["dry", "normal"],
    concerns: ["dryness"],
    ingredients: ["shea butter", "jojoba oil", "aloe vera"],
    routineStep: "moisturizer",
    rating: 4.1,
    reviewCount: 45,
    isNew: false,
    isBestSeller: false,
    countInStock: 30,
  },
  {
    name: "Whipped Shea Body Butter",
    description: "Intense hydration for very dry skin. Ultra-rich formula that melts into the skin.",
    price: 32,
    comparePrice: 40,
    categorySlug: "bodycare",
    images: [
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["ULTRA HYDRATING"],
    skinTypes: ["dry", "extra dry"],
    concerns: ["ashen skin", "dryness"],
    ingredients: ["raw shea butter", "cocoa butter", "almond oil"],
    routineStep: "moisturize",
    rating: 4.7,
    reviewCount: 132,
    isNew: true,
    isBestSeller: true,
    countInStock: 40,
  },
  {
    name: "Lavender Calm Bath Salts",
    description: "Relaxing bath salts infused with lavender essential oil and epson salts for a peaceful soak.",
    price: 22,
    comparePrice: 28,
    categorySlug: "bodycare",
    images: [
      "https://images.unsplash.com/photo-1570194065650-d99fb4b8ccb0?q=80&w=800&auto=format&fit=crop",
    ],
    tags: ["RELAXING"],
    skinTypes: ["all"],
    concerns: ["stress", "muscle fatigue"],
    ingredients: ["epson salt", "dead sea salt", "lavender oil"],
    routineStep: "bath",
    rating: 4.8,
    reviewCount: 94,
    isNew: false,
    isBestSeller: false,
    countInStock: 60,
  },
  {
    name: "Eucalyptus Refresh Body Wash",
    description: "Invigorating body wash with eucalyptus and peppermint to wake up your senses.",
    price: 26,
    comparePrice: 32,
    categorySlug: "bodycare",
    images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop"],
    tags: ["REFRESHING"],
    skinTypes: ["all"],
    concerns: ["dullness"],
    ingredients: ["eucalyptus oil", "peppermint", "aloe"],
    routineStep: "cleanse",
    rating: 4.5,
    reviewCount: 112,
    isNew: true,
    isBestSeller: false,
    countInStock: 80,
  },
  {
    name: "Vitamin E Healing Hand Cream",
    description: "Fast-absorbing hand cream that heals dry, cracked skin with vitamin E and calendula.",
    price: 18,
    comparePrice: 24,
    categorySlug: "bodycare",
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop"],
    tags: ["HEALING"],
    skinTypes: ["dry", "sensitive"],
    concerns: ["dryness", "cracked skin"],
    ingredients: ["vitamin e", "calendula", "shea butter"],
    routineStep: "moisturizer",
    rating: 4.9,
    reviewCount: 305,
    isNew: false,
    isBestSeller: true,
    countInStock: 120,
  },

  // ─────────────── FRAGRANCE ADDITIONS ───────────────
  {
    name: "Midnight Orchid EDP",
    description: "A mysterious blend of black orchid, dark chocolate and patchouli. Sophisticated and alluring.",
    price: 105,
    comparePrice: 125,
    categorySlug: "fragrance",
    images: ["https://images.unsplash.com/photo-1547881338-64913593f1c2?q=80&w=800&auto=format&fit=crop"],
    tags: ["SOPHISTICATED"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["black orchid", "patchouli", "spices"],
    routineStep: "fragrance",
    rating: 4.8,
    reviewCount: 156,
    isNew: true,
    isBestSeller: false,
    countInStock: 25,
  },
  {
    name: "Spiced Sandalwood Mist",
    description: "A warm, grounding mist with notes of creamy sandalwood and toasted cardamom.",
    price: 45,
    comparePrice: 55,
    categorySlug: "fragrance",
    images: ["https://images.unsplash.com/photo-1557170334-a9632e77c6e4?q=80&w=800&auto=format&fit=crop"],
    tags: ["WARM"],
    skinTypes: ["all"],
    concerns: ["sensitivity"],
    ingredients: ["sandalwood", "cardamom", "vanilla"],
    routineStep: "fragrance",
    rating: 4.6,
    reviewCount: 89,
    isNew: false,
    isBestSeller: false,
    countInStock: 45,
  },

  // ─────────────── HAIR MASK ───────────────
  {
    name: "Deep Recovery Macadamia Mask",
    description: "Ultimate hydration for parched locks. Macadamia oil penetrates deep to restore elasticity.",
    price: 48,
    comparePrice: 58,
    categorySlug: "hairmask",
    images: ["https://images.unsplash.com/photo-1519735891097-3b8a330aeecb?q=80&w=800&auto=format&fit=crop"],
    tags: ["INTENSE"],
    skinTypes: ["all"],
    concerns: ["dryness", "brittleness"],
    ingredients: ["macadamia oil", "almond oil", "vitamin b5"],
    routineStep: "treatment",
    rating: 4.9,
    reviewCount: 210,
    isNew: true,
    isBestSeller: true,
    countInStock: 35,
  },
  {
    name: "Overnight Shine Sleep Mask",
    description: "Wake up to luminosity. This weightless mask works while you sleep to smooth cuticles.",
    price: 52,
    comparePrice: 62,
    categorySlug: "hairmask",
    images: ["https://images.unsplash.com/photo-1527799820374-dcf8d9d4a3ef?q=80&w=800&auto=format&fit=crop"],
    tags: ["OVERNIGHT"],
    skinTypes: ["all"],
    concerns: ["dullness", "frizz"],
    ingredients: ["silk proteins", "jojoba oil", "lavender"],
    routineStep: "treatment",
    rating: 4.7,
    reviewCount: 94,
    isNew: true,
    isBestSeller: false,
    countInStock: 50,
  },
  {
    name: "Biotin Boost Scalp Mask",
    description: "Strengthens from the root. Biotin and caffeine stimulate the scalp for thicker-looking hair.",
    price: 55,
    comparePrice: 65,
    categorySlug: "hairmask",
    images: ["https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?q=80&w=800&auto=format&fit=crop"],
    tags: ["STRENGTHENING"],
    skinTypes: ["all"],
    concerns: ["thinning", "weakness"],
    ingredients: ["biotin", "caffeine", "rosemary"],
    routineStep: "treatment",
    rating: 4.8,
    reviewCount: 167,
    isNew: false,
    isBestSeller: true,
    countInStock: 30,
  },
];

export const blogs = [
  {
    title: "The Ultimate Skincare Routine for Glowing Skin",
    slug: "ultimate-skincare-routine-glowing-skin",
    excerpt: "Discover the step-by-step guide to achieving a radiant complexion with our top product picks.",
    content: "Achieving glowing skin isn't just about one product; it's about a consistent routine. Start with a gentle cleanser to remove impurities, followed by a balancing toner. Next, apply a vitamin C serum to brighten and even out your skin tone. Don't forget to moisturize and, most importantly, apply SPF every single day. In this post, we dive deep into each step and why it matters for your skin health.",
    authorName: "Sarah Johnson",
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=800&auto=format&fit=crop",
    tags: ["Skincare", "Glowing Skin", "Beauty Tips"],
  },
  {
    title: "5 Makeup Trends to Watch in 2026",
    slug: "5-makeup-trends-2026",
    excerpt: "From 'Glass Skin' to bold graphic liners, here are the trends that will dominate the beauty world this year.",
    content: "The beauty world is constantly evolving, and 2026 is no exception. This year, we're seeing a move towards 'maximalist minimalism'—combining natural, dewy skin with one bold statement feature. Think neon eyeliners paired with barely-there foundation. We also explore the rise of sustainable packaging and how it's influencing the products we choose.",
    authorName: "Michael Chen",
    image: "https://images.unsplash.com/photo-1512496115851-a1c8e04d2448?q=80&w=800&auto=format&fit=crop",
    tags: ["Makeup", "Trends", "2026"],
  },
  {
    title: "Why Scalp Care is the New Haircare",
    slug: "scalp-care-new-haircare",
    excerpt: "Healthy hair starts at the root. Learn why you should be treating your scalp with the same care as your face.",
    content: "For too long, we've focused only on the strands of our hair, neglecting the foundation they grow from: the scalp. A healthy scalp environment is crucial for strong, shiny hair. From exfoliating scrubs to stimulating oils, we discuss the best ways to detoxify and nourish your scalp for optimal hair growth.",
    authorName: "Elena Rodriguez",
    image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?q=80&w=800&auto=format&fit=crop",
    tags: ["Haircare", "Scalp Care", "Wellness"],
  },
];
